server:
  custom.proxy.basePath: ${SERVER_BASEPATH:}
  servlet.context-path: /api

security:
  oauth2:
    disabled: ${SECURITY_OAUTH2_DISABLED:true}

keycloak:
  auth-server-url: ${SECURITY_KEYCLOAK_URL:https://keycloak:8080/}
  realm: ${SECURITY_KEYCLOAK_REALM:csat-planning}
  resource: ${SECURITY_KEYCLOAK_CLIENT_ID:planning}
  public-client: true

planning:
  repository:
    url: ${REPOSITORY_DATA_URL:}
    username: ${REPOSITORY_DATA_USERNAME:}
    password: ${REPOSITORY_DATA_PASSWORD:}

    task_definitions_graph: ${TASK_DEFINITIONS_GRAPH:http://onto.fel.cvut.cz/ontologies/csat-maintenance/task-card-definitions}

  persistence:
    driver: cz.cvut.kbss.ontodriver.sesame.SesameDataSource
    language: en