server:
  custom.proxy.basePath: ${SERVER_BASEPATH:}
  servlet.context-path: /api
  ssl:
    enabled: ${SERVER_SSL_ENABLED:false}
    key-store-type: ${SERVER_SSL_KEY_STORE_TYPE:PKCS12}
    key-store: ${SERVER_SSL_KEY_STORE:classpath:keystore/keystore.p12}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD:RDP1PiT3oBl5pD1}
    key-alias: ${SERVER_SSL_KEY_ALIAS:dashboard}

security:
  oauth2:
    disabled: ${SECURITY_OAUTH2_DISABLED:false}

keycloak:
  auth-server-url: ${SECURITY_KEYCLOAK_URL:https://keycloak:8080/}
  realm: ${SECURITY_KEYCLOAK_REALM:csat-planning}
  resource: ${SECURITY_KEYCLOAK_CLIENT_ID:planning}
  public-client: true


planning:
  repository:
    url: ${REPOSITORY_DATA_URL:}
    username: ${REPOSITORY_DATA_USERNAME:}
    password: ${REPOSITORY_DATA_PASSWORD:}

    task_definitions_graph: ${TASK_DEFINITIONS_GRAPH:http://onto.fel.cvut.cz/ontologies/csat-maintenance/task-card-definitions}
    task_mapping_graph: ${TASK_MAPPING_GRAPH:http://onto.fel.cvut.cz/ontologies/csat-maintenance/task-mapping-graph}

  persistence:
    driver: cz.cvut.kbss.ontodriver.rdf4j.Rdf4jDataSource
    language: en