server.servlet.context-path: /api

planning:
  repository:
    url: ${REPOSITORY_DATA_URL:}
    username: ${REPOSITORY_DATA_USERNAME:}
    password: ${REPOSITORY_DATA_PASSWORD:}

    task_definitions_graph: ${TASK_DEFINITIONS_GRAPH:http://onto.fel.cvut.cz/ontologies/csat-maintenance/task-card-definitions}

  persistence:
    driver: cz.cvut.kbss.ontodriver.sesame.SesameDataSource
    language: en