PREFIX mapper: <http://www.ontotext.com/mapper/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dc_terms: <http://purl.org/dc/terms/>
PREFIX cm: <http://onto.fel.cvut.cz/ontologies/csat-maintenance/>

SELECT ?taskCard ?taskCardCode ?MPDTASK ?title ?team ?phase ?taskType ?aircraftModel ?area ?elPower ?hydPower ?jacks {
        ?taskCard rdfs:subClassOf cm:task-card ;
                  cm:id ?taskCardCode;
                  cm:task-for-model ?aircraftModel.

        OPTIONAL {?taskCard cm:has-general-task-type ?taskType}
        OPTIONAL {?taskCard cm:has-main-scope ?team}
        OPTIONAL {?taskCard cm:task-for-phase ?phase;}
        OPTIONAL {?taskCard cm:has-mpdtask ?MPDTASK;}
        OPTIONAL {?taskCard rdfs:label ?title;}
        OPTIONAL {?taskCard dc_terms:description ?title;}
        OPTIONAL {?taskCard cm:task-for-area ?area;}
        OPTIONAL {?taskCard cm:required-el-power-restrictions ?elPower;}
        OPTIONAL {?taskCard cm:required-hyd-power-restrictions ?hydPower;}
        OPTIONAL {?taskCard cm:required-jack-restrictions ?jacks;}
}