PREFIX cm: <http://onto.fel.cvut.cz/ontologies/csat-maintenance/>
PREFIX spif: <http://spinrdf.org/spif#>
PREFIX ofn:  <http://www.ontotext.com/sparql/functions/>

SELECT DISTINCT ?wp ?task ?referencedTask ?issueTime ?endTime (MIN(?st) as ?derivedStart) (MAX(?et) as ?derivedEnd) (SUM(ofn:asMillis(?et - ?st)) as ?derivedWorkTime) (ofn:asMillis(?derivedEnd - ?derivedStart) as ?derivedDuration) where {
    OPTIONAL{
        ?wp cm:is-repair-of ?aircraft.
        OPTIONAL{
            ?aircraft cm:model ?aircraftModel.
        }
    }

    ?task cm:is-part-of-workpackage ?wp .
    ?task a ?taskType .
    ?taskType a cm:task-type .

    OPTIONAL{?taskType cm:id ?taskTypeId . }
    OPTIONAL{?taskType cm:references-ata-code ?ataCode . }

    OPTIONAL{
        ?taskType rdfs:subClassOf ?superTaskType .
        FILTER(?superTaskType in (cm:task-card, cm:maintenance-work-order, cm:scheduled-work-order))
        BIND(replace(str(?superTaskType), "^.*/([^/]+)$", "$1") as ?taskCategory)
    }

    OPTIONAL{
        ?task cm:references-task ?referencedTask
    }

    ?task cm:issue-time ?issueTime.
    ?task cm:end-time ?endTime.
    ?session cm:is-part-of-maintenance-task ?task .

    ?session cm:start-date ?sDate.
    ?session cm:start-time ?sTime.
    BIND(CONCAT(str(?sDate),"T", str(?sTime), IF(!contains(str(?sTime), "+"), "+02:00", "")) as ?start)

    BIND(spif:parseDate(?start, "yyyy-MM-dd'T'HH:mm") as ?st)

    ?session cm:end-date ?eDate.
    ?session cm:end-time ?eTime.
    BIND(CONCAT(str(?eDate),"T", str(?eTime), IF(!contains(str(?sTime), "+"), "+02:00", "")) as ?end)
    BIND(spif:parseDate(?end, "yyyy-MM-dd'T'HH:mm") as ?et)

} GROUP BY ?task ?issueTime ?endTime
