PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX cm: <http://onto.fel.cvut.cz/ontologies/csat-maintenance/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ofn: <http://www.ontotext.com/sparql/functions/>
PREFIX spif: <http://spinrdf.org/spif#>
PREFIX ufo: <http://onto.fel.cvut.cz/ontologies/ufo/>


#SELECT ?wp ?acmodel ?type (sample(?ttLabel) as ?typeLabel) ?scope ?taskcat (spif:dateFormat(?st,"yyyy-MM-dd") as ?date) (str(?st) as ?start) (str(?et) as ?end) ( str(ofn:asMillis(?et - ?st)) as ?dur)
SELECT ?wp ?acmodel ?type (?ttLabel as ?typeLabel) ?scope ?scopeLabel ?taskcat (?sDate as ?date) (str(?st) as ?start) (str(?et) as ?end) (str(ofn:asMillis(?et - ?st)) as ?dur)
WHERE
{
    ?tt cm:is-part-of-workpackage ?wpuri.
    ?wpuri cm:id ?wp;
        cm:is-repair-of ?ac.
    ?ac cm:model ?acmodel.

    ?t cm:is-part-of-maintenance-task ?tt;
        cm:has-scope ?scopeGroup.
    ?scopeGroup cm:has-abbreviation ?scope.
    ?tt a ?tType.
    BIND(cm:task-card as ?cls)
    ?tType a owl:Class;
        cm:id ?type;
        rdfs:subClassOf ?cls.
#    FILTER(?cls IN (cm:task-card, cm:scheduled-work-order, cm:maintenance-work-orde))


    OPTIONAL{
        ?t cm:task-description ?ttLabel.
    }
    ?w cm:performs ?t.
#    ?scopeGroup rdfs:label ?scope.
    ?   t cm:start-date ?sDate;
       cm:start-time ?sTime;
       cm:end-date ?eDate;
       cm:end-time ?eTime;
    BIND(spif:parseDate(CONCAT(?sDate,"T", ?sTime),"dd.MM.yyyy'T'hh:mm") as ?st)
    BIND(spif:parseDate(CONCAT(?eDate,"T", ?eTime),"dd.MM.yyyy'T'hh:mm") as ?et)


    # select specific aircraft
#    FITER(?acmodel in ("738" "73G" "73H" "73J" "73W" "B735"))
#    FILTER(!contains(?wp, "SICHR") ) # this workpackages do not contain TCs
#    FILTER(!contains(?wp, "/L-") )
#    BIND(replace(str(?tType), "^.*/([^/]+)$", "$1") as ?type)
    BIND(replace(str(?scopeGroup), "^.*/([^/]+)$", "$1") as ?scopeLabel)
    BIND(replace(str(?cls), "^.*/([^/]+)$", "$1") as ?taskcat)
}
#GROUP BY ?wp ?acmodel ?type ?scope ?taskcat ?st ?et - group by takes takes too long to calculate
#ORDER BY ?start