PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cm: <http://onto.fel.cvut.cz/ontologies/csat-maintenance/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ofn: <http://www.ontotext.com/sparql/functions/>
PREFIX spif: <http://spinrdf.org/spif#>
PREFIX ufo: <http://onto.fel.cvut.cz/ontologies/ufo/>



PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT DISTINCT ?wp ?taskType WHERE
{
    ?wp a cm:workpackage. 
    ?task a ?taskType.
    ?taskType a cm:task-type .
}