PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cm: <http://onto.fel.cvut.cz/ontologies/csat-maintenance/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ofn: <http://www.ontotext.com/sparql/functions/>
PREFIX spif: <http://spinrdf.org/spif#>
PREFIX ufo: <http://onto.fel.cvut.cz/ontologies/ufo/>



PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT ?wpuri ?wp ?ac ?acmodel ?client ?clientId ?wpStartTime ?wpEndTime ?wpScheduledStartTime ?wpScheduledEndTime WHERE
{
    ?wpuri a cm:workpackage.
    ?wpuri cm:id ?wp.

   OPTIONAL{
        ?wpuri cm:has-client ?client.
        OPTIONAL{ ?client cm:id ?clientId}
   }

    # aircraft
    OPTIONAL{
        ?wpuri cm:is-repair-of ?ac.
        OPTIONAL{
            ?ac cm:model ?acmodel.
        }
    }

    # temporal properties of WP
    OPTIONAL{?wpuri cm:workpackage-start-time ?wpStartTime.}
    OPTIONAL{?wpuri cm:workpackage-end-time ?wpEndTime.}
    OPTIONAL{?wpuri cm:workpackage-scheduled-start-time ?wpScheduledStartTime.}
    OPTIONAL{?wpuri cm:workpackage-scheduled-end-time ?wpScheduledEndTime.}
}