PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX vann: <http://purl.org/vocab/vann/>
PREFIX apd: <http://onto.fel.cvut.cz/ontologies/slovník/agendový/popis-dat/pojem/>
PREFIX caf: <http://onto.fel.cvut.cz/ontologies/slovnik/slovnik-komponent-a-zavad---novy/pojem/>
PREFIX termit: <http://onto.fel.cvut.cz/ontologies/application/termit/pojem/>
PREFIX csat-mp: <http://onto.fel.cvut.cz/ontolgies/csat/mp-voc/>
PREFIX csat-mpt: <http://onto.fel.cvut.cz/ontolgies/csat/mp-voc/pojem/>



CONSTRUCT{
  ?voc a apd:slovník, owl:Ontology;
    dcterms:creator ?creator;
	dcterms:created ?created;
    dcterms:title ?title ;
	dcterms:description ?description ;
	bibo:status ?status ; 
        vann:preferredNamespacePrefix ?prefix ;
        vann:preferredNamespaceUri ?namespace ;
        owl:imports ?glossary , ?model ;
        owl:versionIRI  ?revisionIRI ;
    apd:má-glosář ?glossary;
    apd:má-model ?model.
    
  
  ?glossary
	a apd:glosář, skos:ConceptScheme;
	skos:hasTopConcept ?termIRI .

  ?model
    a apd:model .

  ?termIRI a skos:Concept;
	skos:inScheme ?glossary ;
	skos:prefLabel ?termLang ;
	termit:je-draft true.
	
  ?termIRI skos:prefLabel ?termLang2.
  ?termIRI skos:altLabel ?termLang3.
  ?termIRI skos:altLabel ?abbreviation.
  ?termIRI skos:broader ?cat.
	# skos:definition ?es ;
	# skos:prefLabel ?termCs ;
	# skos:scopeNote ?es.
	
}WHERE{
	BIND("en" as ?lang)
	BIND("cs" as ?lang2)
	BIND("version/0.0.1" as ?revision)
	BIND("Martin Kala" as ?creator)
	BIND("2017-03-01" as ?created)
	BIND(strlang("Draft",?lang) as ?status) # bibo:draft
	BIND(strlang("CSAT Aircraft Maintenance Terminology", ?lang) as ?title )
	BIND(strlang("CSAT vocabulary containing relevant aircraft related terminology used in maintenance documentation", ?lang) as ?descriptoin )
	BIND("csat-mp" as ?prefix)
	BIND(str(csat-mp:) as ?namespace)
	BIND("pojem/" as ?termSeparator)
	
	BIND(IF(?category = "C", caf:component, if(?category = "F", caf:failure, ?category)) as ?cat)
	# BIND(?category as ?cat)
	# BIND(strlang("", ?lang) as ?es)
	BIND(strlang(?label, ?lang) as ?termLang)
	BIND(strlang(?label2, ?lang2) as ?termLang2)
	BIND(strlang(?label3, ?lang2) as ?termLang3)
	BIND(strlang(?abr, ?lang) as ?abbreviation)
	BIND(IRI(concat(str(csat-mp:), ?termSeparator, replace(?termId, "[\\s/\\\\\\)\\(]", "-")) ) as ?termIRI)
	BIND(IRI(replace(str(csat-mp:), "/$","")) as ?voc)
	BIND(IRI(concat(str(csat-mp:), ?revision)) as ?revisionIRI)
	BIND(IRI(concat(str(csat-mp:), "glossary")) as ?glossary)
	BIND(IRI(concat(str(csat-mp:), "model")) as ?model)
}
